name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get install build-essential
          sudo apt-get install flex
          sudo apt-get install bison
          sudo apt-get install texinfo
        if: matrix.os == 'ubuntu-latest'
      - name: Build toolchain
        run: |
          ./build/build.sh
